# Generated by Django 4.1 on 2022-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=200, verbose_name='Nombre del Query')),
                ('select', models.CharField(choices=[('', ''), ('S1', 'Seleccion 1'), ('S2', 'Seleccion 2'), ('S3', 'Seleccion 3'), ('S4', 'Seleccion 4'), ('S5', 'Seleccion 5')], max_length=10, verbose_name='Pestaña Desplegables')),
                ('fecha', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['-created'],
            },
        ),
    ]
